#DATABASE
spring:
  datasource:
    username: 'root'
    url: 'jdbc:mysql://localhost:3310/pokemon_ao_db'
    password: 'root'
  jpa:
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.MySQLDialect'
    hibernate:
      ddl-auto: 'validate'
