version: "3"
services:
  pokemon_ao_db:
    image: mysql:latest
    container_name: pokemon_ao_db
    networks:
      - common
    ports:
      - "3310:3306"
    environment:
      - MYSQL_DATABASE=pokemon_ao_db
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql

  pokemon_ao_application:
    image: openjdk:17-jdk-slim
    container_name: pokemon_ao_application
    volumes:
      - ../common-properties/customProperties.yaml:/home/customProperties.yaml
      - ./properties/application.yaml:/home/application.yaml
      - ./PokemonAO-0.0.1-SNAPSHOT.jar:/home/PokemonAO-0.0.1-SNAPSHOT.jar
      - ../db/unknownDataType.sql:/home/unknownDataType.sql
    command: ["java", "-jar", "/home/PokemonAO-0.0.1-SNAPSHOT.jar"]
    depends_on:
      - pokemon_ao_db
    networks:
      - common
    ports:
      - "8080:8080"

networks:
  common:
    name: common
